[package]
name = "tdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23.1"
clap = { version = "3.0.14", features = ["derive"] }
syscalls = "0.5.0"
once_cell = "1.9.0"
gimli = "0.26.1"
object = "0.28.3"
memmap = "0.7.0"
proc-maps = "0.2.0"
env_logger = "0.9.0"
hex = "0.4.3"
symbolic = { version = "8.6.0", default-features = false, features = [
    "demangle",
] }

# TUI用
#tui = "0.17"
#crossterm = "0.22"
