[package]
name = "rdbg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.23.1"
clap = { version = "3.0.13", features = ["derive"] }
syscalls = "0.5"
libc = "0.2.112"
once_cell = "1.9"
tui = "0.17"
crossterm = "0.22"
